mod support;

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use agent_matters_capabilities::profiles::{
    CompileProfileBuildRequest, CompileProfileBuildResult, compile_profile_build,
};
use agent_matters_core::domain::DiagnosticSeverity;
use tempfile::TempDir;

use support::fixtures::fixture_path;

fn copy_dir(from: &Path, to: &Path) {
    fs::create_dir_all(to).unwrap();
    for entry in fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let source = entry.path();
        let target = to.join(entry.file_name());
        if source.is_dir() {
            copy_dir(&source, &target);
        } else {
            fs::copy(&source, &target).unwrap();
        }
    }
}

fn valid_repo() -> TempDir {
    let tmp = TempDir::new().unwrap();
    copy_dir(&fixture_path("catalogs/valid"), tmp.path());
    tmp
}

fn compile(repo_root: &Path, state: &Path) -> CompileProfileBuildResult {
    let result = compile_profile_build(CompileProfileBuildRequest {
        repo_root: repo_root.to_path_buf(),
        user_state_dir: state.to_path_buf(),
        native_home_dir: Some(native_home_with_codex_auth(state)),
        profile: "github-researcher".to_string(),
        runtime: Some("codex".to_string()),
        env: BTreeMap::new(),
    })
    .unwrap();
    assert_eq!(result.diagnostics, Vec::new());
    result
}

fn write(root: &Path, rel: &str, body: &str) {
    let path = root.join(rel);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(path, body).unwrap();
}

fn native_home_with_codex_auth(root: &Path) -> std::path::PathBuf {
    let home = root.join("native-home");
    fs::create_dir_all(home.join(".codex")).unwrap();
    fs::write(home.join(".codex/auth.json"), br#"{"token":"test"}"#).unwrap();
    home
}

fn append_profile_marker(repo: &Path, marker: &str) {
    let path = repo.join("profiles/renamed-profile-dir/manifest.toml");
    let body = fs::read_to_string(&path).unwrap();
    fs::write(
        path,
        format!("{body}\n[instructions_output]\nmarkers = \"{marker}\"\n"),
    )
    .unwrap();
}

fn agents_md(result: &CompileProfileBuildResult) -> String {
    let build = result.build.as_ref().unwrap();
    fs::read_to_string(build.home_dir.join("AGENTS.md")).unwrap()
}

#[test]
fn compiled_agents_md_uses_profile_instruction_order_and_html_markers() {
    let repo = valid_repo();
    let state = TempDir::new().unwrap();

    let content = agents_md(&compile(repo.path(), state.path()));

    assert_eq!(content, expected_html_marked_agents_md());
    assert!(content.is_ascii());
}

#[test]
fn top_notice_mode_avoids_per_fragment_comments() {
    let repo = valid_repo();
    let state = TempDir::new().unwrap();
    write(
        repo.path(),
        "defaults/markers.toml",
        r#"
        [instructions_output]
        markers = "top-notice"
        "#,
    );

    let content = agents_md(&compile(repo.path(), state.path()));

    assert!(content.starts_with("<!-- Generated by agent-matters"));
    assert!(!content.contains("agent-matters:begin"));
    assert!(content.contains("# Helioy Core\n\nWork from local files first."));
    assert!(content.contains("# GitHub Researcher\n\nFocus on repository structure"));
    assert!(content.find("# Helioy Core") < content.find("# GitHub Researcher"));
}

#[test]
fn none_mode_emits_only_fragment_content() {
    let repo = valid_repo();
    let state = TempDir::new().unwrap();
    write(
        state.path(),
        "config.toml",
        r#"
        [instructions_output]
        markers = "none"
        "#,
    );

    let content = agents_md(&compile(repo.path(), state.path()));

    assert_eq!(content, expected_unmarked_agents_md());
}

#[test]
fn profile_marker_override_wins_over_user_default() {
    let repo = valid_repo();
    let state = TempDir::new().unwrap();
    write(
        state.path(),
        "config.toml",
        r#"
        [instructions_output]
        markers = "top-notice"
        "#,
    );
    append_profile_marker(repo.path(), "none");

    let content = agents_md(&compile(repo.path(), state.path()));

    assert_eq!(content, expected_unmarked_agents_md());
}

#[test]
fn missing_instruction_fragment_file_reports_compile_diagnostic() {
    let repo = valid_repo();
    let state = TempDir::new().unwrap();
    fs::remove_file(
        repo.path()
            .join("catalog/instructions/helioy-core/AGENTS.md"),
    )
    .unwrap();

    let result = compile_profile_build(CompileProfileBuildRequest {
        repo_root: repo.path().to_path_buf(),
        user_state_dir: state.path().to_path_buf(),
        native_home_dir: Some(native_home_with_codex_auth(state.path())),
        profile: "github-researcher".to_string(),
        runtime: Some("codex".to_string()),
        env: BTreeMap::new(),
    })
    .unwrap();

    assert!(result.build.is_none());
    assert_eq!(result.diagnostics.len(), 1);
    assert_eq!(result.diagnostics[0].severity, DiagnosticSeverity::Error);
    assert_eq!(
        result.diagnostics[0].code,
        "profile.build-plan.input-read-failed"
    );
}

#[test]
fn generated_file_stays_ascii_unless_source_content_requires_unicode() {
    let repo = valid_repo();
    let state = TempDir::new().unwrap();
    write(
        repo.path(),
        "catalog/agents/github-researcher/AGENT.md",
        "# GitHub Researcher\n\nCafe\u{301} context is allowed when source needs it.\n",
    );

    let content = agents_md(&compile(repo.path(), state.path()));

    assert!(!content.is_ascii());
    assert!(content.contains("Cafe\u{301} context"));
}

fn expected_html_marked_agents_md() -> String {
    [
        "<!-- agent-matters:begin id=\"instruction:helioy-core\" source=\"catalog/instructions/helioy-core/AGENTS.md\" -->",
        "# Helioy Core",
        "",
        "Work from local files first. Keep runtime homes generated.",
        "<!-- agent-matters:end id=\"instruction:helioy-core\" -->",
        "",
        "<!-- agent-matters:begin id=\"agent:github-researcher\" source=\"catalog/agents/github-researcher/AGENT.md\" -->",
        "# GitHub Researcher",
        "",
        "Focus on repository structure, issue context, and implementation constraints.",
        "<!-- agent-matters:end id=\"agent:github-researcher\" -->",
        "",
    ]
    .join("\n")
}

fn expected_unmarked_agents_md() -> String {
    [
        "# Helioy Core",
        "",
        "Work from local files first. Keep runtime homes generated.",
        "",
        "# GitHub Researcher",
        "",
        "Focus on repository structure, issue context, and implementation constraints.",
        "",
    ]
    .join("\n")
}
