use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use std::str::FromStr;

use agent_matters_core::catalog::{
    CapabilityIndexRecord, MANIFEST_FILE_NAME, ProfileIndexRecord, RuntimeCompatibilitySummary,
};
use agent_matters_core::domain::{CapabilityId, ProfileId, ProfileKind, RuntimeId};
use agent_matters_core::manifest::{
    ProfileManifest, ProfileRuntimeManifest, ProfileRuntimesManifest,
};
use agent_matters_core::runtime::FingerprintBuilder;

use super::{JitProfileResolveError, JitProfileResolveRequest, JitSessionCache};

const JIT_PROFILE_SCHEMA_VERSION: u16 = 1;
const SESSION_CACHE_DIR_NAME: &str = "session-cache";
const JIT_DIR_NAME: &str = "jit";

pub(super) fn write_session_cache_profile(
    request: &JitProfileResolveRequest,
    capability_ids: &[String],
    reasons: &[&str],
) -> Result<JitSessionCache, JitProfileResolveError> {
    let fingerprint = jit_fingerprint(request, capability_ids);
    let profile_body = format!("jit-{fingerprint}");
    let profile_id = ProfileId::new(profile_body.clone()).map_err(|source| {
        JitProfileResolveError::ProfileId {
            body: profile_body.clone(),
            source,
        }
    })?;
    let cache_dir = request
        .user_state_dir
        .join(SESSION_CACHE_DIR_NAME)
        .join(JIT_DIR_NAME)
        .join(profile_id.as_str());
    let manifest_path = cache_dir.join(MANIFEST_FILE_NAME);
    let manifest = generated_profile_manifest(
        profile_id,
        &request.runtime,
        capability_ids,
        &format!(
            "Generated JIT profile for task: {}",
            request.task_text.trim()
        ),
    )?;
    let body = format!(
        "# Generated by agent-matters JIT resolver.\n# Reasons: {}\n{}",
        reasons.join("; "),
        toml::to_string_pretty(&manifest).map_err(|source| {
            JitProfileResolveError::EncodeManifest {
                path: manifest_path.clone(),
                source,
            }
        })?
    );
    fs::create_dir_all(&cache_dir).map_err(|source| JitProfileResolveError::WriteManifest {
        path: cache_dir.clone(),
        source,
    })?;
    fs::write(&manifest_path, body).map_err(|source| JitProfileResolveError::WriteManifest {
        path: manifest_path.clone(),
        source,
    })?;

    Ok(JitSessionCache {
        profile_id: manifest.id.to_string(),
        cache_dir,
        profile_manifest_path: manifest_path,
    })
}

pub(super) fn generated_profile_record(
    profile_id: &str,
    cache_dir: &Path,
    runtime: &str,
    capabilities: &BTreeMap<String, CapabilityIndexRecord>,
    capability_ids: &[String],
) -> ProfileIndexRecord {
    let mut runtimes = BTreeMap::new();
    runtimes.insert(
        runtime.to_string(),
        RuntimeCompatibilitySummary {
            supported: true,
            model: None,
        },
    );
    let (manifest_capabilities, manifest_instructions): (Vec<_>, Vec<_>) =
        capability_ids.iter().cloned().partition(|id| {
            capabilities
                .get(id)
                .is_none_or(|record| record.kind != "agent" && record.kind != "instruction")
        });
    let capability_count = manifest_capabilities.len();
    let instruction_count = manifest_instructions.len();

    ProfileIndexRecord {
        id: profile_id.to_string(),
        kind: "task".to_string(),
        summary: "Generated JIT profile.".to_string(),
        capabilities: manifest_capabilities,
        instructions: manifest_instructions,
        scope: Default::default(),
        source_path: cache_dir.to_string_lossy().to_string(),
        runtimes,
        default_runtime: Some(runtime.to_string()),
        instruction_markers: None,
        capability_count,
        instruction_count,
    }
}

fn generated_profile_manifest(
    profile_id: ProfileId,
    runtime: &str,
    capability_ids: &[String],
    summary: &str,
) -> Result<ProfileManifest, JitProfileResolveError> {
    let runtime_id = RuntimeId::new(runtime.to_string()).map_err(|source| {
        JitProfileResolveError::RuntimeId {
            body: runtime.to_string(),
            source,
        }
    })?;
    let (capabilities, instructions) = split_manifest_capabilities(capability_ids)?;
    let mut entries = BTreeMap::new();
    entries.insert(
        runtime_id.clone(),
        ProfileRuntimeManifest {
            enabled: true,
            model: None,
        },
    );

    Ok(ProfileManifest {
        id: profile_id,
        kind: ProfileKind::Task,
        summary: summary.to_string(),
        capabilities,
        instructions,
        scope: None,
        runtimes: Some(ProfileRuntimesManifest {
            default: Some(runtime_id),
            entries,
        }),
        instructions_output: None,
    })
}

fn split_manifest_capabilities(
    capability_ids: &[String],
) -> Result<(Vec<CapabilityId>, Vec<CapabilityId>), JitProfileResolveError> {
    let mut capabilities = Vec::new();
    let mut instructions = Vec::new();
    for id in capability_ids {
        let parsed =
            CapabilityId::from_str(id).map_err(|source| JitProfileResolveError::CapabilityId {
                id: id.clone(),
                source,
            })?;
        match parsed.kind().as_str() {
            "agent" | "instruction" => instructions.push(parsed),
            _ => capabilities.push(parsed),
        }
    }
    Ok((capabilities, instructions))
}

fn jit_fingerprint(request: &JitProfileResolveRequest, capability_ids: &[String]) -> String {
    let mut builder = FingerprintBuilder::new(JIT_PROFILE_SCHEMA_VERSION);
    builder.write_str(&request.task_text);
    builder.write_str(&request.runtime);
    if let Some(path) = &request.workspace_path {
        builder.write_str(&path.to_string_lossy());
    }
    for id in capability_ids {
        builder.write_str(id);
    }
    builder.finish_hex()
}
