//! Build script. Reads `tools.toml` at the workspace root and regenerates
//! `src/cli/generated_help.rs` with one `pub const` per documented piece
//! of CLI help text. The generated file is checked in so that clippy and
//! rust-analyzer see stable constant names even without a fresh build.
//!
//! The sibling `context-matters` project uses the same pattern and also
//! emits an MCP schema module plus a SKILL.md; agent-matters does not yet
//! expose either surface, so only the CLI generator lives here. When those
//! surfaces arrive they should read from the same `tools.toml` entries.

use indexmap::IndexMap;
use serde::Deserialize;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct ToolsToml {
    tools: IndexMap<String, ToolDef>,
}

#[derive(Deserialize)]
struct ToolDef {
    cli_about: String,
    #[serde(default)]
    params: Vec<ParamDef>,
}

#[derive(Deserialize)]
struct ParamDef {
    name: String,
    cli_help: Option<String>,
}

fn main() {
    println!("cargo:rerun-if-changed=../../tools.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=AGENT_MATTERS_GIT_SHA");

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    emit_version();

    let tools_toml_path = Path::new(&manifest_dir).join("../../tools.toml");

    let content = fs::read_to_string(&tools_toml_path)
        .unwrap_or_else(|e| panic!("Failed to read tools.toml: {e}"));

    let parsed: ToolsToml =
        toml::from_str(&content).unwrap_or_else(|e| panic!("Failed to parse tools.toml: {e}"));

    let help_rs = generate_cli_help(&parsed.tools);

    let cli_dir = Path::new(&manifest_dir).join("src/cli");
    fs::create_dir_all(&cli_dir).unwrap_or_else(|e| panic!("Failed to create src/cli/: {e}"));

    write_if_changed(&cli_dir.join("generated_help.rs"), &help_rs);
}

fn emit_version() {
    let package_version = std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION not set");
    let version = match std::env::var("AGENT_MATTERS_GIT_SHA") {
        Ok(sha) if !sha.trim().is_empty() => format!("{package_version}+{}", sha.trim()),
        _ => package_version,
    };
    println!("cargo:rustc-env=AGENT_MATTERS_VERSION={version}");
}

fn write_if_changed(path: &Path, content: &str) {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == content
    {
        return;
    }
    fs::write(path, content).unwrap_or_else(|e| panic!("Failed to write {}: {e}", path.display()));
}

fn generate_cli_help(tools: &IndexMap<String, ToolDef>) -> String {
    let mut lines = vec![
        "// AUTO-GENERATED by build.rs from tools.toml. Do not edit.".to_string(),
        "// Regenerate by running `cargo build -p agent-matters-cli` after".to_string(),
        "// editing the workspace root tools.toml.".to_string(),
        "#![allow(clippy::all)]".to_string(),
        String::new(),
    ];

    for (tool_key, tool) in tools {
        let prefix = tool_key.to_uppercase().replace('-', "_");

        lines.push("#[rustfmt::skip]".to_string());
        lines.push(format!(
            "pub const {prefix}_ABOUT: &str = \"{}\";",
            rust_escape(tool.cli_about.trim())
        ));

        for param in &tool.params {
            let Some(help) = &param.cli_help else {
                continue;
            };
            let param_upper = param.name.to_uppercase().replace('-', "_");
            lines.push("#[rustfmt::skip]".to_string());
            lines.push(format!(
                "pub const {prefix}_{param_upper}_HELP: &str = \"{}\";",
                rust_escape(help)
            ));
        }

        lines.push(String::new());
    }

    lines.join("\n")
}

fn rust_escape(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}
