//! Top level clap surface and dispatch entry point.
//!
//! The command tree is noun first: each top level variant of [`Command`]
//! carries a nested enum listing the verbs for that noun. Keeping the nouns
//! in their own modules lets each file stay single responsibility.
//!
//! Help content comes from two sources:
//!   * [`generated_help`]: generated by `build.rs` from the workspace root
//!     `tools.toml`. Owns per-command `ABOUT` and per-argument `HELP`.
//!   * [`help_text`]: hand authored. Owns the top level long about and
//!     per-command `AFTER_HELP` example blocks.
//!
//! Handlers are thin adapters that delegate to `agent-matters-capabilities`.
//! Commands without landed use cases return a clear `not yet implemented`
//! error so the CLI surface is discoverable and testable.

use clap::{CommandFactory, Parser, Subcommand, ValueEnum};
use clap_complete::Shell;
use std::path::PathBuf;

pub mod capabilities;
pub mod doctor;
pub mod generated_help;
pub mod help_text;
mod profile_render;
pub mod profiles;
pub mod sources;

/// Top level `agent-matters` CLI.
#[derive(Debug, Parser)]
#[command(
    name = "agent-matters",
    version,
    about = "Local first runtime profile system for Codex, Claude, and future CLI runtimes",
    long_about = help_text::LONG_ABOUT
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Command>,
}

/// Top level command groups.
#[derive(Debug, Subcommand)]
pub enum Command {
    /// Manage runtime profiles.
    Profiles {
        #[command(subcommand)]
        command: profiles::ProfilesCmd,
    },
    /// Manage capabilities.
    Capabilities {
        #[command(subcommand)]
        command: capabilities::CapabilitiesCmd,
    },
    /// Manage catalog sources.
    Sources {
        #[command(subcommand)]
        command: sources::SourcesCmd,
    },
    /// Diagnose catalog, runtime, and auth setup.
    #[command(
        long_about = generated_help::DOCTOR_ABOUT,
        after_help = help_text::DOCTOR_AFTER_HELP
    )]
    Doctor {
        /// Emit machine readable JSON instead of the grouped human report.
        #[arg(short = 'j', long, help = generated_help::DOCTOR_JSON_HELP)]
        json: bool,
    },
    /// Generate shell completion script for the `agent-matters` binary.
    Completions {
        /// Target shell: bash, zsh, fish, powershell, elvish.
        #[arg(value_enum)]
        shell: Shell,
    },
}

/// Target runtime for compile and use commands.
#[derive(Debug, Clone, Copy, ValueEnum)]
#[value(rename_all = "lowercase")]
pub enum Runtime {
    /// OpenAI Codex CLI.
    Codex,
    /// Anthropic Claude Code CLI.
    Claude,
}

impl Runtime {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Codex => "codex",
            Self::Claude => "claude",
        }
    }
}

/// Parse the top level CLI and dispatch to the appropriate handler.
///
/// Returns the intended process exit code. A bare invocation with no
/// subcommand prints long help and exits zero; all other paths rely on
/// handler return values.
pub fn dispatch(cli: Cli) -> anyhow::Result<i32> {
    match cli.command {
        None => {
            Cli::command().print_long_help()?;
            println!();
            Ok(0)
        }
        Some(Command::Profiles { command }) => profiles::dispatch(command),
        Some(Command::Capabilities { command }) => capabilities::dispatch(command),
        Some(Command::Sources { command }) => sources::dispatch(command),
        Some(Command::Doctor { json }) => doctor::run(json),
        Some(Command::Completions { shell }) => {
            let mut cmd = Cli::command();
            clap_complete::generate(shell, &mut cmd, "agent-matters", &mut std::io::stdout());
            Ok(0)
        }
    }
}

pub(crate) fn default_catalog_paths() -> anyhow::Result<(PathBuf, PathBuf)> {
    let repo_root = std::env::current_dir()?;
    let user_state_dir = match std::env::var_os("AGENT_MATTERS_STATE_DIR") {
        Some(path) => PathBuf::from(path),
        None => {
            let home = std::env::var_os("HOME")
                .map(PathBuf::from)
                .ok_or_else(|| anyhow::anyhow!("HOME is not set"))?;
            home.join(".agent-matters")
        }
    };

    Ok((repo_root, user_state_dir))
}

pub(crate) fn render_runtime_names(
    runtimes: &std::collections::BTreeMap<
        String,
        agent_matters_core::catalog::RuntimeCompatibilitySummary,
    >,
) -> String {
    if runtimes.is_empty() {
        return "none".to_string();
    }

    runtimes
        .iter()
        .map(|(runtime, support)| {
            if support.supported {
                runtime.clone()
            } else {
                format!("{runtime}:disabled")
            }
        })
        .collect::<Vec<_>>()
        .join(",")
}

pub(crate) fn emit_diagnostics(diagnostics: &[agent_matters_core::domain::Diagnostic]) {
    for diagnostic in diagnostics {
        eprintln!(
            "{} {}: {}",
            diagnostic_severity(diagnostic.severity),
            diagnostic.code,
            diagnostic.message
        );
        if let Some(hint) = &diagnostic.recovery_hint {
            eprintln!("  hint: {hint}");
        }
    }
}

fn diagnostic_severity(severity: agent_matters_core::domain::DiagnosticSeverity) -> &'static str {
    match severity {
        agent_matters_core::domain::DiagnosticSeverity::Info => "info",
        agent_matters_core::domain::DiagnosticSeverity::Warning => "warning",
        agent_matters_core::domain::DiagnosticSeverity::Error => "error",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cli_definition_is_valid() {
        Cli::command().debug_assert();
    }

    #[test]
    fn help_mentions_runtime_profiles() {
        let help = Cli::command().render_long_help().to_string();
        assert!(help.contains("runtime"));
        assert!(help.contains("profile"));
    }
}
