// AUTO-GENERATED by build.rs from tools.toml. Do not edit.
// Regenerate by running `cargo build -p agent-matters-cli` after
// editing the workspace root tools.toml.
#![allow(clippy::all)]

#[rustfmt::skip]
pub const PROFILES_LIST_ABOUT: &str = "List profiles discovered in the local catalog.\n\nEach profile line shows the profile id, kind, enabled runtimes, scope enforcement, and summary. Use `profiles show` to inspect a single profile in detail.";
#[rustfmt::skip]
pub const PROFILES_LIST_JSON_HELP: &str = "Emit a JSON result object with profiles, index metadata, and diagnostics";

#[rustfmt::skip]
pub const PROFILES_SHOW_ABOUT: &str = "Show a single profile and its resolved capability inventory.\n\nPrints the profile manifest, the ordered list of capabilities it includes, the instruction fragments those capabilities contribute, and the runtime settings that would apply for each registered runtime adapter.";
#[rustfmt::skip]
pub const PROFILES_SHOW_PROFILE_HELP: &str = "Profile identifier (matches the `id` field in its manifest)";
#[rustfmt::skip]
pub const PROFILES_SHOW_JSON_HELP: &str = "Emit machine readable JSON instead of the human rendering";

#[rustfmt::skip]
pub const PROFILES_RESOLVE_ABOUT: &str = "Resolve a task into an existing profile or local JIT profile.\n\nUses only local catalog profiles and capabilities. When a clear capability composition is found, writes a generated profile manifest under the session cache so the result can feed compile without mutating authored catalog files.";
#[rustfmt::skip]
pub const PROFILES_RESOLVE_TASK_HELP: &str = "Task text to resolve into local profile material";
#[rustfmt::skip]
pub const PROFILES_RESOLVE_PATH_HELP: &str = "Workspace path for task context. Defaults to the current working directory.";
#[rustfmt::skip]
pub const PROFILES_RESOLVE_RUNTIME_HELP: &str = "Target runtime for candidate filtering and build planning";
#[rustfmt::skip]
pub const PROFILES_RESOLVE_JSON_HELP: &str = "Emit machine readable JSON instead of the human resolver summary";

#[rustfmt::skip]
pub const PROFILES_COMPILE_ABOUT: &str = "Compile a runtime home for the given profile without activating it.\n\nWrites an immutable build under the managed builds directory, fingerprinted by resolved content. No existing `.codex` or `.claude` directory is touched. Use `profiles use` to point a runtime at the compiled build.";
#[rustfmt::skip]
pub const PROFILES_COMPILE_PROFILE_HELP: &str = "Profile identifier to compile";
#[rustfmt::skip]
pub const PROFILES_COMPILE_RUNTIME_HELP: &str = "Target runtime for the compiled build";
#[rustfmt::skip]
pub const PROFILES_COMPILE_JSON_HELP: &str = "Emit machine readable JSON instead of the human summary";

#[rustfmt::skip]
pub const PROFILES_USE_ABOUT: &str = "Activate the given profile for the target runtime.\n\nCompiles the profile if needed and points the runtime's managed home (`CODEX_HOME` or `CLAUDE_CONFIG_DIR`) at the resulting build. Does not launch the runtime binary; prints the launch command the caller should run.";
#[rustfmt::skip]
pub const PROFILES_USE_PROFILE_HELP: &str = "Profile identifier to activate";
#[rustfmt::skip]
pub const PROFILES_USE_PATH_HELP: &str = "Directory to activate the profile in. Defaults to the current working directory.";
#[rustfmt::skip]
pub const PROFILES_USE_RUNTIME_HELP: &str = "Target runtime for activation. Defaults through profile, user config, or single enabled runtime.";
#[rustfmt::skip]
pub const PROFILES_USE_JSON_HELP: &str = "Emit machine readable JSON launch instructions";

#[rustfmt::skip]
pub const CAPABILITIES_LIST_ABOUT: &str = "List capabilities discovered in the local catalog.\n\nEach row includes the capability id, kind, runtime support, provenance state, and summary. Use `capabilities show` to inspect files, requirements, source paths, and overlay metadata.";
#[rustfmt::skip]
pub const CAPABILITIES_LIST_JSON_HELP: &str = "Emit a JSON result object with capabilities, index metadata, and diagnostics";

#[rustfmt::skip]
pub const CAPABILITIES_SHOW_ABOUT: &str = "Show a single capability and its metadata.\n\nPrints the manifest details, source path, included files, runtime compatibility, requirements, provenance, and overlay metadata for one exact capability id.";
#[rustfmt::skip]
pub const CAPABILITIES_SHOW_CAPABILITY_HELP: &str = "Capability identifier";
#[rustfmt::skip]
pub const CAPABILITIES_SHOW_JSON_HELP: &str = "Emit machine readable JSON instead of the human rendering";

#[rustfmt::skip]
pub const CAPABILITIES_DIFF_ABOUT: &str = "Diff a capability's local overlay against its vendor record.\n\nOnly meaningful for capabilities imported from an external source. Reports file level additions, deletions, and modifications so the caller can decide whether to re-sync with upstream or promote the overlay.";
#[rustfmt::skip]
pub const CAPABILITIES_DIFF_CAPABILITY_HELP: &str = "Capability identifier";
#[rustfmt::skip]
pub const CAPABILITIES_DIFF_JSON_HELP: &str = "Emit machine readable JSON instead of the human diff report";

#[rustfmt::skip]
pub const SOURCES_SEARCH_ABOUT: &str = "Search a registered source for entries matching a query.\n\nMVP sources: `skills.sh`. Additional sources (for example the MCP Registry) arrive with their adapters under ALP-1916. Returns a ranked list of locators suitable for passing to `sources import`.";
#[rustfmt::skip]
pub const SOURCES_SEARCH_SOURCE_HELP: &str = "Source identifier (for example `skills.sh`)";
#[rustfmt::skip]
pub const SOURCES_SEARCH_QUERY_HELP: &str = "Free form search query";
#[rustfmt::skip]
pub const SOURCES_SEARCH_JSON_HELP: &str = "Emit machine readable JSON instead of the human table";

#[rustfmt::skip]
pub const SOURCES_IMPORT_ABOUT: &str = "Import a capability from a source by locator.\n\nWrites normalized capability files into the catalog, preserves raw source material under `vendor`, and records provenance so future syncs and diffs can detect drift.";
#[rustfmt::skip]
pub const SOURCES_IMPORT_LOCATOR_HELP: &str = "Source specific locator (scheme determined by the source adapter)";
#[rustfmt::skip]
pub const SOURCES_IMPORT_JSON_HELP: &str = "Emit machine readable JSON instead of the human summary";
#[rustfmt::skip]
pub const SOURCES_IMPORT_UPDATE_HELP: &str = "Update an existing imported capability instead of reporting a conflict";

#[rustfmt::skip]
pub const IMPORT_ABOUT: &str = "Import an existing Codex or Claude runtime home.\n\nRuntime and profile default from the path when possible. Default mode is a dry run that reports the profile, capabilities, vendor records, skipped credential files, and conflicts that would be produced. Use `--write` after reviewing the report to create catalog content.";
#[rustfmt::skip]
pub const IMPORT_PATH_HELP: &str = "Path to the existing runtime config directory";
#[rustfmt::skip]
pub const IMPORT_PROFILE_HELP: &str = "Profile id to create. Defaults to `imported-<path-name>`.";
#[rustfmt::skip]
pub const IMPORT_RUNTIME_HELP: &str = "Runtime to use when detection from the path is ambiguous";
#[rustfmt::skip]
pub const IMPORT_WRITE_HELP: &str = "Write the import after reviewing the dry run report";
#[rustfmt::skip]
pub const IMPORT_JSON_HELP: &str = "Emit machine readable JSON instead of the human report";

#[rustfmt::skip]
pub const DOCTOR_ABOUT: &str = "Diagnose catalog, runtime, and auth setup.\n\nRuns the full suite of local integrity checks: catalog discovery, manifest schema, capability requirement resolution, required environment variables, overlay and vendor consistency, runtime adapter reachability, and credential allowlist presence. Reports findings grouped by severity.";
#[rustfmt::skip]
pub const DOCTOR_JSON_HELP: &str = "Emit machine readable JSON instead of the grouped human report";
